#!/bin/bash
echo ""
echo "🔍 Running pre-push checks..."
echo ""

# Analyze code
flutter analyze > analyze_output.txt

# Check if flutter analyze returned non-zero (i.e. has errors)
if [ $? -ne 0 ]; then
    echo "❌ Flutter analyze failed:"
    cat analyze_output.txt
    rm analyze_output.txt
    exit 1
fi

# Check specifically for unused imports (even if warning)
if grep -q "info • Unused import" analyze_output.txt; then
    echo "❌ Unused import(s) found. Please remove them before pushing:"
    grep "info • Unused import" analyze_output.txt
    rm analyze_output.txt
    exit 1
fi

echo "✅ Flutter analyze passed."
rm analyze_output.txt


# # Format check
# FORMAT_OUTPUT=$(dart format --set-exit-if-changed . 2>&1)
# EXIT_CODE=$?

# if [[ $EXIT_CODE -ne 0 ]]; then
#     echo "❌ Code formatting issues found:"
#     echo "$FORMAT_OUTPUT"
#     exit 1
# else
#     echo "✅ Code is properly formatted."
# fi

# Format check with auto-correct
FORMAT_OUTPUT=$(dart format . 2>&1)

if [[ "$FORMAT_OUTPUT" == *"Formatted "* ]]; then
    # echo "❌ Code formatting issues found"
    # echo "$FORMAT_OUTPUT"
    echo "✅ Code formatted"
else
    echo "✅ Code formatting is correct"
fi



echo "🧪 Running tests..."
flutter test
if [ $? -ne 0 ]; then
    echo "❌ Tests failed!"
    exit 1
fi

echo ""
echo "---------------------------------------------"
echo ""
echo "✅ All checks passed. Proceeding with push."
echo ""
echo "---------------------------------------------"
echo ""
exit 0
